### ISSUE TITLE
Rpi 4

### ISSUE THREAD

**Issue by gev** [WJWH/HPi#8]
Hi! Is this library compatible with rpi 4?

**Comment by WJWH** [comment]
Hello! I haven't made any changes to this repo for quite a while, but since it's basically a Haskell wrapper around the bcm2835 library (which works fine for the RPi4) I don't see why not. The library just doesn't need a lot of changes since the GPIO functionality is pretty much complete.

(Also, in the README for this repo it says that it works for Pi versions up to and including 4. I don't have a RPi4, but I assume I know what I was doing back when I wrote that :sweat_smile: )

**Comment by gev** [comment]
Will test!

**Comment by alt-romes** [comment]
I've been using the library with Pi4 (using the 1.75 version of bcm2835), it works wonderfully.

We can probably close this issue 👍.
